# SQLite version 3.x
# gem install sqlite3
#
# Ensure the SQLite 3 gem is defined in your Gemfile
# gem 'sqlite3'

# Amazon AWS Production
# production:
#  adapter: mysql2
#  encoding: utf8
#  database: <%= ENV['RDS_DB_NAME'] %>
#  username: <%= ENV['RDS_USERNAME'] %>
#  password: <%= ENV['RDS_PASSWORD'] %>
#  host: <%= ENV['RDS_HOSTNAME'] %>
#  port: <%= ENV['RDS_PORT'] %>


development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: pg_db_on_11_feb # pg_db_on_4_feb
  username: postgres
  password: postgres
  host: localhost
  port: 5432
# development:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   database: d5gplihnrmuhgp
#   username: cgqmoimdevhcvm
#   password: BSib5K0ZAgokA3z8nMNTJXZC2y
#   host: ec2-54-243-62-232.compute-1.amazonaws.com
#   port: 5432
# development:
#   adapter: mysql2
#   encoding: utf8
#   database: ebdb
#   username: ebroot
#   password: Caball666­
#   host: aarx1hstoz87bg.c8aipepaiyph.us-west-1.rds.amazonaws.com
#   port: 3306

# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/filmzu_development.sqlite3

# development:
#  adapter: mysql2
#  encoding: utf8
#  database: ebdb
#  username: ebroot
#  password: 
#  host: aa2v09ynvkki2ar.c8aipepaiyph.us-west-1.rds.amazonaws.com
#  port: 3306
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   host: localhost
#   # For details on connection pooling, see rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: 5
#   username: postgres
#   password: postgres

# development:
#   <<: *default
#   database: filmzu_development
 #Dev postgres credentials
 # development:
 #   adapter: postgresql
 #   encoding: unicode
 #   pool: 5
 #   database: filmzu_one
 #   username: postgres
 #   password: postgres
 #   host: localhost
 #   port: 5432

# Cloud Heroku Development
# development:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   database: d5gplihnrmuhgp
#   username: cgqmoimdevhcvm
#   password: BSib5K0ZAgokA3z8nMNTJXZC2y
#   host: aa2v09ynvkki2ar.c8aipepaiyph.us-west-1.rds.amazonaws.com
#   port: 5432

#Dev postgres credentials
#development:
#  adapter: postgresql
#  encoding: unicode
#  pool: 5
#  database: filmzu_one
#  username: postgres
#  password: nimbu
#  host: localhost
#  port: 5432

#production:
#  adapter: postgresql
#  encoding: unicode
#  pool: 5
#  database: filmzu_development
#  username: postgres
#  password: nimbu
#  host: localhost
#  port: 5432

# Rupert Development
# development:
# adapter: mysql2
# pool: 5
# database: caball_production
# username: root
# password: root
# host: localhost

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
# test:
# adapter: postgresql
# database: caball_test
# host: localhost
# username: postgres
# password:
# pool: 5
# timeout: 5000
